<?php

namespace Domain\Entity\Repository;

use Domain\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function save(User $user)
    {
        $em = $this->getEntityManager();
        $em->persist($user);
        $em->flush($user);
    }
    
    public function findByUserName($username)
    {
        return $this->findOneBy(array('username' => $username));
    }
    
    public function findByApiKey($key)
    {
        return $this->findOneBy(array('apiKey' => $key));
    }
}
