language: php
php:
  - '5.6'

before_script:
  - composer require satooshi/php-coveralls
  - composer install

script:
  - phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
