<?php

namespace AppBundle\Repository;

/**
 * MotorcycleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotorcycleRepository extends \Doctrine\ORM\EntityRepository
{
}
