# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    ##################Rtaranto\Application##################
    #Endpoint Action
    app.action.bikers.post_action:
        class: Rtaranto\Application\Service\Endpoint\Action\Biker\BikersPostAction
        arguments: ['@app.parameters_binder.biker', '@app.validator', '@infra.repository.biker']
    app.action.bikers.get_action:
        class: Rtaranto\Application\Service\Endpoint\Action\Biker\BikersGetAction
        arguments: ['@infra.repository.biker']
    app.action.bikers.patch_action:
        class: Rtaranto\Application\Service\Endpoint\Action\Biker\BikersPatchAction
        arguments: ['@app.parameters_binder.biker', '@app.validator', '@infra.repository.biker']
    app.bikers.delete:
        class: Rtaranto\Application\Service\Endpoint\Action\Biker\DeleteBiker
        arguments: ['@infra.repository.biker']
    app.action.cget_bikers_factory:
        class: Rtaranto\Application\Service\Endpoint\Action\Factory\CgetBikersActionFactory
        
    #Validator
    app.validator:
        class: Rtaranto\Application\Service\Validator\Validator
        arguments: ['@validator']
    #Security
    app.user_registration:
        class: Rtaranto\Application\Service\Security\UserRegistrationService
        arguments: ['@domain.factory.normal_user', '@infra.repository.user', '@app.validator']
    app.login:
        class: Rtaranto\Application\Service\Security\StatelessLoginService
        arguments: ['@infra.repository.user', '@infra.password_validator', '@app.token_generator' ]
    app.token_generator:
        class: Rtaranto\Application\Service\Security\TokenGenerator
        arguments: ['@infra.repository.user', '@app.authentication_token_factory']
    app.authentication_token_factory:
        class: Rtaranto\Application\Factory\AuthenticationTokenFactory
    app.token_authenticator:
        class: Rtaranto\Application\Service\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager', '@router']
    #Parameters Binder
    app.parameters_binder.biker:
        class: Rtaranto\Application\Service\ParametersBinder\ParametersBinder
        arguments: ['@form.factory', 'Rtaranto\Presentation\Form\Biker\BikerDTOType']
        
    ##################Domain##################
    domain.factory.normal_user:
        class: Rtaranto\Domain\Entity\Factory\NormalUserFactory
        arguments: ['@security.password_encoder']
        
    ##################Rtaranto\Infrastructure##################
    infra.repository.user:
        class: Rtaranto\Infrastructure\Repository\DoctrineUserRepository
        arguments: ['@doctrine.orm.entity_manager']
    infra.repository.biker:
        class: Rtaranto\Infrastructure\Repository\DoctrineBikerRepository
        arguments: ['@doctrine.orm.entity_manager']
    infra.password_validator:
        class: Rtaranto\Application\Service\Security\SaltedPasswordValidator
        arguments: ['@security.encoder_factory']
        