# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    ##################Application##################
    ###Endpoint Action
    app.action.bikers.post_action:
        class: Rtaranto\Application\EndpointAction\Biker\PostBikerAction
        factory: ["@app.action.post_biker_factory", createPostAction]
    app.action.bikers.get_action:
        class: Rtaranto\Application\EndpointAction\Biker\GetBikerAction
        arguments: ['@infra.repository.biker']
    app.action.bikers.patch_action:
        class: Rtaranto\Application\EndpointAction\Biker\PatchBikerAction
        factory: ["@app.action.patch_biker_factory", createPatchAction]
    app.bikers.delete_action:
        class: Rtaranto\Application\EndpointAction\Biker\DeleteBikerAction
        arguments: ['@infra.repository.biker']
    ##Performed Oil Change
    app.performed_oil_change.patch_action:
        class: Rtaranto\Application\EndpointAction\OilChange\PatchPerformedOilChangeAction
        factory: ["@app.action.factory.patch_performed_oil_change", createPatchAction]
    app.performed_oil_change.post_action:
        class: Rtaranto\Application\EndpointAction\OilChange\PostPerformedOilChangeAction
        factory: ["@app.action.factory.post_performed_oil_change", createPostAction]
    ##Performed Rear Tire Change
    app.performed_rear_tire_change.post_action:
        class: Rtaranto\Application\EndpointAction\RearTireChange\PostPerformedRearTireChangeAction
        factory: ["@app.action.factory.post_performed_rear_tire_change", createPostAction]
    app.performed_rear_tire_change.patch_action:
        class: Rtaranto\Application\EndpointAction\RearTireChange\PatchPerformedRearTireChangeAction
        factory: ["@app.action.factory.patch_performed_rear_tire_change", createPatchAction]
    ##Performed Front Tire Change
    app.performed_front_tire_change.post_action:
        class: Rtaranto\Application\EndpointAction\FrontTireChange\PostPerformedFrontTireChangeAction
        factory: ["@app.action.factory.post_performed_front_tire_change", createPostAction]
    app.performed_front_tire_change.patch_action:
        class: Rtaranto\Application\EndpointAction\FrontTireChange\PatchPerformedFrontTireChangeAction
        factory: ["@app.action.factory.patch_performed_front_tire_change", createPatchAction]
        
    ##Endpoint Action Factory
    app.action.cget_bikers_factory:
        class: Rtaranto\Application\EndpointAction\Factory\Biker\CgetBikersActionFactory
        arguments: ['@doctrine.orm.entity_manager']
    app.action.patch_biker_factory:
        class: Rtaranto\Application\EndpointAction\Factory\Biker\PatchBikerActionFactory
        arguments: ['@form.factory', '@validator', '@doctrine.orm.entity_manager']
    app.action.post_biker_factory:
        class: Rtaranto\Application\EndpointAction\Factory\Biker\PostBikerActionFactory
        arguments: ['@form.factory', '@validator', '@doctrine.orm.entity_manager']    
    #Performed Oil Change
    app.action.factory.patch_performed_oil_change:
        class: Rtaranto\Application\EndpointAction\Factory\OilChange\PatchPerformedOilChangeActionFactory
        arguments: ['@form.factory', '@validator', '@doctrine.orm.entity_manager']
    app.action.factory.post_performed_oil_change:
        class: Rtaranto\Application\EndpointAction\Factory\OilChange\PostPerformedOilChangeActionFactory
        arguments: ['@form.factory', '@validator', '@doctrine.orm.entity_manager']
    #Performed Rear Tire Change
    app.action.factory.post_performed_rear_tire_change:
        class: Rtaranto\Application\EndpointAction\Factory\RearTireChange\PostPerformedRearTireChangeActionFactory
        arguments: ['@form.factory', '@validator', '@doctrine.orm.entity_manager']
    app.action.factory.patch_performed_rear_tire_change:
        class: Rtaranto\Application\EndpointAction\Factory\RearTireChange\PatchPerformedRearTireChangeActionFactory
        arguments: ['@form.factory', '@validator', '@doctrine.orm.entity_manager']
    #Performed Front Tire Change
    app.action.factory.post_performed_front_tire_change:
        class: Rtaranto\Application\EndpointAction\Factory\FrontTireChange\PostPerformedFrontTireChangeActionFactory
        arguments: ['@form.factory', '@validator', '@doctrine.orm.entity_manager']
    app.action.factory.patch_performed_front_tire_change:
        class: Rtaranto\Application\EndpointAction\Factory\FrontTireChange\PatchPerformedFrontTireChangeActionFactory
        arguments: ['@form.factory', '@validator', '@doctrine.orm.entity_manager']
        
    #Validator
    app.validator:
        class: Rtaranto\Application\Service\Validator\Validator
        arguments: ['@validator']
    app.kms:
        class: AppBundle\Validator\Constraints\KmsDoNotExceedCurKmsDrivenValidator
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: validator.constraint_validator, alias: kms_do_not_exceeds_cur_kms_driven }
    #Security
    app.biker_registration:
        class: Rtaranto\Application\Service\Security\BikerRegistrationService
        arguments: ['@app.user_registration', '@infra.repository.biker', '@app.validator']
    app.user_registration:
        class: Rtaranto\Application\Service\Security\UserRegistrationService
        arguments: ['@domain.factory.user', '@infra.repository.user', '@app.validator']
    app.login:
        class: Rtaranto\Application\Service\Security\StatelessLoginService
        arguments: ['@infra.repository.user', '@infra.password_validator', '@app.token_generator' ]
    app.token_generator:
        class: Rtaranto\Application\Service\Security\TokenGenerator
        arguments: ['@infra.repository.user', '@app.authentication_token_factory']
    app.authentication_token_factory:
        class: Rtaranto\Application\Service\Security\Factory\AuthenticationTokenFactory
    app.token_authenticator:
        class: Rtaranto\Application\Service\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager', '@router']
        
    ##################Domain##################
    domain.factory.user:
        class: Rtaranto\Domain\Entity\Factory\UserFactory
        arguments: ['@security.password_encoder']
        
    ##################Rtaranto\Infrastructure##################
    infra.repository.user:
        class: Rtaranto\Infrastructure\Repository\DoctrineUserRepository
        arguments: ['@doctrine.orm.entity_manager']
    infra.repository.biker:
        class: Rtaranto\Infrastructure\Repository\DoctrineBikerRepository
        arguments: ['@doctrine.orm.entity_manager']
    infra.password_validator:
        class: Rtaranto\Application\Service\Security\SaltedPasswordValidator
        arguments: ['@security.encoder_factory']
        