# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    ##################Application##################
    #Endpoint Action
    app.action.bikers.post_action:
        class: Rtaranto\Application\EndpointAction\Biker\PostBikerAction
        factory: ["@app.action.post_biker_factory", createPostAction]
    app.action.bikers.get_action:
        class: Rtaranto\Application\EndpointAction\Biker\GetBikerAction
        arguments: ['@infra.repository.biker']
    app.action.bikers.patch_action:
        class: Rtaranto\Application\EndpointAction\Biker\PatchBikerAction
        factory: ["@app.action.patch_biker_factory", createPatchAction]
    app.bikers.delete_action:
        class: Rtaranto\Application\EndpointAction\Biker\DeleteBikerAction
        arguments: ['@infra.repository.biker']
    #Endpoint Action Factory
    app.action.cget_bikers_factory:
        class: Rtaranto\Application\EndpointAction\Factory\Biker\CgetBikersActionFactory
        arguments: ['@doctrine.orm.entity_manager']
    app.action.patch_biker_factory:
        class: Rtaranto\Application\EndpointAction\Factory\Biker\PatchBikerActionFactory
        arguments: ['@form.factory', '@validator', '@doctrine.orm.entity_manager']
    app.action.post_biker_factory:
        class: Rtaranto\Application\EndpointAction\Factory\Biker\PostBikerActionFactory
        arguments: ['@form.factory', '@validator', '@doctrine.orm.entity_manager']
        
    #Validator
    app.validator:
        class: Rtaranto\Application\Service\Validator\Validator
        arguments: ['@validator']
    #Security
    app.biker_registration:
        class: Rtaranto\Application\Service\Security\BikerRegistrationService
        arguments: ['@app.user_registration', '@infra.repository.biker', '@app.validator']
    app.user_registration:
        class: Rtaranto\Application\Service\Security\UserRegistrationService
        arguments: ['@domain.factory.user', '@infra.repository.user', '@app.validator']
    app.login:
        class: Rtaranto\Application\Service\Security\StatelessLoginService
        arguments: ['@infra.repository.user', '@infra.password_validator', '@app.token_generator' ]
    app.token_generator:
        class: Rtaranto\Application\Service\Security\TokenGenerator
        arguments: ['@infra.repository.user', '@app.authentication_token_factory']
    app.authentication_token_factory:
        class: Rtaranto\Application\Service\Security\Factory\AuthenticationTokenFactory
    app.token_authenticator:
        class: Rtaranto\Application\Service\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager', '@router']
        
    ##################Domain##################
    domain.factory.user:
        class: Rtaranto\Domain\Entity\Factory\UserFactory
        arguments: ['@security.password_encoder']
        
    ##################Rtaranto\Infrastructure##################
    infra.repository.user:
        class: Rtaranto\Infrastructure\Repository\DoctrineUserRepository
        arguments: ['@doctrine.orm.entity_manager']
    infra.repository.biker:
        class: Rtaranto\Infrastructure\Repository\DoctrineBikerRepository
        arguments: ['@doctrine.orm.entity_manager']
    infra.password_validator:
        class: Rtaranto\Application\Service\Security\SaltedPasswordValidator
        arguments: ['@security.encoder_factory']
        