# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    #Application
    app.service.register_user:
        class: Application\Service\RegisterUserService
        arguments: ['@domain.factory.normal_user', '@infra.repository.user', '@validator']
        
    #Domain
    domain.factory.normal_user:
        class: Domain\Entity\Factory\NormalUserFactory
        arguments: ['@security.password_encoder']
        
    #Infrastructure
    infra.token_authenticator:
        class: Infrastructure\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager', '@router']
    infra.repository.user:
        class: Infrastructure\Repository\DoctrineUserRepository
        arguments: ['@doctrine.orm.entity_manager']
        
        