# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    ###Application###
    app.service.register_user:
        class: Application\Service\Security\RegisterUserService
        arguments: ['@domain.factory.normal_user', '@infra.repository.user', '@app.validator']
    #Endpoint Service 
    app.endpoint.bikers:
        class: Application\Service\Endpoint\BikersEndpointService
        arguments: ['@app.action.bikers.post_action']
    #Endpoint Action
    app.action.bikers.post_action:
        class: Application\Service\Endpoint\Action\Biker\BikersPostAction
        arguments: ['@infra.repository.biker', '@app.validator']
    #Validator
    app.validator:
        class: Application\Service\Validator\Validator
        arguments: ['@validator']
        
    #Domain
    domain.factory.normal_user:
        class: Domain\Entity\Factory\NormalUserFactory
        arguments: ['@security.password_encoder']
        
    #Infrastructure
    infra.token_authenticator:
        class: Infrastructure\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager', '@router']
    infra.repository.user:
        class: Infrastructure\Repository\DoctrineUserRepository
        arguments: ['@doctrine.orm.entity_manager']
    infra.repository.biker:
        class: Infrastructure\Repository\DoctrineBikerRepository
        arguments: ['@doctrine.orm.entity_manager']
        
        