api_v1_login:
    type: rest
    resource: Rtaranto\Presentation\Controller\LoginController 
    name_prefix: "api_v1_"
    
api_v1_registration:
    type: rest
    resource: Rtaranto\Presentation\Controller\RegistrationController
    name_prefix: "api_v1_"
    
api_v1_entry_point:
    type: rest
    resource: Rtaranto\Presentation\Controller\EntryPointController
    name_prefix: "api_v1_"
    
api_bikers:
    type:         rest
    resource:     Rtaranto\Presentation\Controller\BikerController
    name_prefix:  api_v1_
    
api_motorcycles:
    type:         rest
    resource:     Rtaranto\Presentation\Controller\MotorcycleController
    name_prefix:  api_v1_
    
api_oil_changes:
    type:     rest
    parent:   api_motorcycles
    resource: Rtaranto\Presentation\Controller\OilChangeController
    name_prefix:  api_v1_
    
api_rear_tire_changes:
    type:     rest
    parent:   api_motorcycles
    resource: Rtaranto\Presentation\Controller\RearTireChangeController
    name_prefix:  api_v1_
    
api_front_tire_changes:
    type:     rest
    parent:   api_motorcycles
    resource: Rtaranto\Presentation\Controller\FrontTireChangeController
    name_prefix:  api_v1_
