Rtaranto\Domain\Entity\PerformedMaintenance:
    exclusion_policy: ALL
    discriminator:
        field_name: type
        map:
            performedoilchange: Rtaranto\Domain\Entity\PerformedOilChange
            performedreartirechange: Rtaranto\Domain\Entity\PerformedRearTireChange
    properties:
        id:
            groups: [view]
        kmsDriven:
            groups: [view]
        date:
            type: DateTime<'Y-m-d'>
            groups: [view]