Domain\Entity\Biker:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 50
            unique: true
        email:
            type: string
            length: 255
            unique: true