Rtaranto\Domain\Entity\Maintenance:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        oilchangeperformer: Rtaranto\Domain\Entity\OilChangeMaintenance
    
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
                
    fields:
        kmsPerMaintenance:
            type: integer
            nullable: true
            options:
                unsigned: true
                
    oneToOne:
        motorcycle:
            targetEntity: Motorcycle
            joinColumn:
                name: motorcycle_id
                referencedColumnName: id
                onDelete: CASCADE
                
    oneToMany:
        performedMaintenances:
            targetEntity: PerformedMaintenance
            mappedBy: maintenance
            cascade: ["persist", "remove"]
            orphanRemoval: true