Rtaranto\Domain\Entity\MaintenancePerformer:
    type: entity
    table: null
    repositoryClass: Rtaranto\Infrastructure\Repository\DoctrineMaintenancePerformerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        motorcycle:
            targetEntity: Motorcycle
            joinColumn:
                name: motorcycle_id
                referencedColumnName: id
                onDelete: cascade
        oilChangeMaintenance:
            targetEntity: OilChangeMaintenance
            joinColumn:
                name: oilchangemaintenance_id
                referencedColumnName: id
            cascade: ["persist", "remove"]
            orphanRemoval: true
                            
    lifecycleCallbacks: {  }
