Rtaranto\Domain\Entity\MaintenancePerformer:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        oilchangeperformer: Rtaranto\Domain\Entity\OilChangePerformer
    
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
                
    fields:
        kmsPerMaintenance:
            type: integer
            nullable: true
            options:
                unsigned: true
                
    oneToOne:
        motorcycle:
            targetEntity: Motorcycle
            joinColumn:
                name: motorcycle_id
                referencedColumnName: id
                onDelete: cascade
    manyToMany:
        maintenancesPerformed:
            targetEntity: Maintenance
            joinTable:
                name: maintenanceperformers_maintenances
            joinColumns:
                maintenanceperformer_id:
                    referencedColumnName: id
            inverseJoinColumns:
                maintenance_id:
                    referencedColumnName: id
                    unique: true
            cascade: ["persist", "remove"]
            orphanRemoval: true