Rtaranto\Domain\Entity\Maintenance:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        oilchange: Rtaranto\Domain\Entity\OilChange
    
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
                
    fields:
        kmsPerMaintenance:
            type: integer
            nullable: true
            options:
                unsigned: true
                
    oneToOne:
        motorcycle:
            targetEntity: Motorcycle
            joinColumn:
                name: motorcycle_id
                referencedColumnName: id
                onDelete: CASCADE
            
    manyToMany:
        performedMaintenances:
            targetEntity: PerformedMaintenance
            joinTable:
                name: maintenances_performedmaintenances
                joinColumns:
                    maintenance_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    performedmaintenance_id:
                        referencedColumnName: id
                        unique: true
            cascade: ["persist", "remove"]
            orphanRemoval: true