Rtaranto\Domain\Entity\Motorcycle:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        model:
            type: string
            length: '20'
        kmsDriven:
            type: integer
            options:
                unsigned: true
    manyToOne:
        biker:
            targetEntity: Biker
            inversedBy: motorcycles
            joinColumn:
                name: biker_id
                referencedColumnName: id
                
    lifecycleCallbacks: {  }
