Rtaranto\Domain\Entity\PerformedMaintenance:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        oilchange: Rtaranto\Domain\Entity\PerformedOilChange
    repositoryClass: Rtaranto\Infrastructure\Repository\DoctrinePerformedMaintenanceRepository
    
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        kmsDriven:
            type: integer
            options:
                unsigned: true
        date:
            type: date
    manyToOne:
        maintenance:
            targetEntity: Maintenance
            inversedBy: performedMaintenances
            joinColumn:
                name: maintenance_id
                referencedColumnName: id