Rtaranto\Domain\Entity\PerformedMaintenance:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        performedoilchange: Rtaranto\Domain\Entity\PerformedOilChange
        performedreartirechange: Rtaranto\Domain\Entity\PerformedRearTireChange
    
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        kmsDriven:
            type: integer
            options:
                unsigned: true
        date:
            type: date
            
    oneToOne:
        motorcycle:
            targetEntity: Motorcycle
            joinColumn:
                name: motorcycle_id
                referencedColumnName: id
                onDelete: CASCADE