Rtaranto\Domain\Entity\Maintenance:
    properties:
        kmsPerMaintenance:
            - Range:
                min: 0
                max: 100000
                
        performedMaintenances:
            - Valid: ~