Rtaranto\Application\Dto\WarningsConfiguration\OilChangeWarningConfigurationsDTO:
    properties:
        kmsPerMaintenance:
            - Range:
                min: 1
                max: 1000000
        kmsInAdvance:
            - Range:
                min: 0
                max: 1000000