Rtaranto\Application\Dto\Maintenance\PerformedMaintenanceDTO:
    properties:
        date:
            - Date: ~
        kmsDriven:
            - Range:
                min: 0
                max: 1000000