Rtaranto\Application\Dto\Security\UserRegistrationDTO:
    properties:
        username:
            - NotBlank: ~
            - Length:
                min: 8
                max: 50
        password:
            - NotBlank: ~
            - Length:
                min: 6
                max: 4096
        email:
            - NotBlank: ~
            - Email:
                message: Invalid e-mail address.
                checkMX: true