AppBundle\Security\LoginCommand:
    properties:
        username:
            - NotBlank: ~
            - Length:
                min: 3
                max: 50
        password:
            - NotBlank: ~
            - Length:
                min: 6
                max: 4096
        